//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceControlsLanguage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceControlsLanguage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI.Resources.ResourceControlsLanguage", typeof(ResourceControlsLanguage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormCreateSale_btnAgregarCarrito {
            get {
                return ResourceManager.GetString("FormCreateSale:btnAgregarCarrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormCreateSale_btnAtras {
            get {
                return ResourceManager.GetString("FormCreateSale:btnAtras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormCreateSale_btnGenerarFactura {
            get {
                return ResourceManager.GetString("FormCreateSale:btnGenerarFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormCreateSale_btnRemoveItem {
            get {
                return ResourceManager.GetString("FormCreateSale:btnRemoveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormCreateSale_buttonCerrarVenta {
            get {
                return ResourceManager.GetString("FormCreateSale:buttonCerrarVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormCreateSale_gbDetailsCart {
            get {
                return ResourceManager.GetString("FormCreateSale:gbDetailsCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormCreateSale_gBFiltros {
            get {
                return ResourceManager.GetString("FormCreateSale:gBFiltros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormCreateSale_label5 {
            get {
                return ResourceManager.GetString("FormCreateSale:label5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormCreateSale_label7 {
            get {
                return ResourceManager.GetString("FormCreateSale:label7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormCreateSale_label8 {
            get {
                return ResourceManager.GetString("FormCreateSale:label8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormCreateSale_label9 {
            get {
                return ResourceManager.GetString("FormCreateSale:label9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormCreateSale_lblBrandName {
            get {
                return ResourceManager.GetString("FormCreateSale:lblBrandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormCreateSale_lblCart {
            get {
                return ResourceManager.GetString("FormCreateSale:lblCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormCreateSale_lblCatogory {
            get {
                return ResourceManager.GetString("FormCreateSale:lblCatogory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormCreateSale_lblDeliveryDate {
            get {
                return ResourceManager.GetString("FormCreateSale:lblDeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormCreateSale_lblEstadoCliente {
            get {
                return ResourceManager.GetString("FormCreateSale:lblEstadoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormCreateSale_lblInsertDniClient {
            get {
                return ResourceManager.GetString("FormCreateSale:lblInsertDniClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormCreateSale_lblItemsTotal {
            get {
                return ResourceManager.GetString("FormCreateSale:lblItemsTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormCreateSale_lblTotal {
            get {
                return ResourceManager.GetString("FormCreateSale:lblTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormCreateSale_lblTypeInvoice {
            get {
                return ResourceManager.GetString("FormCreateSale:lblTypeInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormLogin_btnChangeLenguage {
            get {
                return ResourceManager.GetString("FormLogin:btnChangeLenguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormLogin_btnLogin {
            get {
                return ResourceManager.GetString("FormLogin:btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormLogin_label2 {
            get {
                return ResourceManager.GetString("FormLogin:label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormLogin_lblErrorMessage {
            get {
                return ResourceManager.GetString("FormLogin:lblErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormLogin_lblSignIn {
            get {
                return ResourceManager.GetString("FormLogin:lblSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormLogin_lnkForgotten {
            get {
                return ResourceManager.GetString("FormLogin:lnkForgotten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormMain_btnClients {
            get {
                return ResourceManager.GetString("FormMain:btnClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormMain_btnCreateSale {
            get {
                return ResourceManager.GetString("FormMain:btnCreateSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormMain_btnEmployees {
            get {
                return ResourceManager.GetString("FormMain:btnEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormMain_btnHelp {
            get {
                return ResourceManager.GetString("FormMain:btnHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormMain_btnLogout {
            get {
                return ResourceManager.GetString("FormMain:btnLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormMain_btnManagerLanguages {
            get {
                return ResourceManager.GetString("FormMain:btnManagerLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormMain_btnOrders {
            get {
                return ResourceManager.GetString("FormMain:btnOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormMain_btnProducts {
            get {
                return ResourceManager.GetString("FormMain:btnProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormMain_btnProfiles {
            get {
                return ResourceManager.GetString("FormMain:btnProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormMain_btnReports {
            get {
                return ResourceManager.GetString("FormMain:btnReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormMain_btnUsers {
            get {
                return ResourceManager.GetString("FormMain:btnUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormMain_lblDateTime {
            get {
                return ResourceManager.GetString("FormMain:lblDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormMain_lblEmail {
            get {
                return ResourceManager.GetString("FormMain:lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormMain_lblName {
            get {
                return ResourceManager.GetString("FormMain:lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormMain_lblPosition {
            get {
                return ResourceManager.GetString("FormMain:lblPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormMain_lnkMyProfile {
            get {
                return ResourceManager.GetString("FormMain:lnkMyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormUserProfile_btnCancel {
            get {
                return ResourceManager.GetString("FormUserProfile:btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormUserProfile_btnChangeLanguage {
            get {
                return ResourceManager.GetString("FormUserProfile:btnChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormUserProfile_btnSaveMyData {
            get {
                return ResourceManager.GetString("FormUserProfile:btnSaveMyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormUserProfile_label1 {
            get {
                return ResourceManager.GetString("FormUserProfile:label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormUserProfile_label14 {
            get {
                return ResourceManager.GetString("FormUserProfile:label14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormUserProfile_label5 {
            get {
                return ResourceManager.GetString("FormUserProfile:label5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormUserProfile_lblConfirmPassword {
            get {
                return ResourceManager.GetString("FormUserProfile:lblConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormUserProfile_lblCurrentPassword {
            get {
                return ResourceManager.GetString("FormUserProfile:lblCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormUserProfile_lblEditMyData {
            get {
                return ResourceManager.GetString("FormUserProfile:lblEditMyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormUserProfile_lblEmail {
            get {
                return ResourceManager.GetString("FormUserProfile:lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormUserProfile_lblFirstName {
            get {
                return ResourceManager.GetString("FormUserProfile:lblFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormUserProfile_lblLastName {
            get {
                return ResourceManager.GetString("FormUserProfile:lblLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormUserProfile_lblName {
            get {
                return ResourceManager.GetString("FormUserProfile:lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormUserProfile_lblName2 {
            get {
                return ResourceManager.GetString("FormUserProfile:lblName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormUserProfile_lblPassword {
            get {
                return ResourceManager.GetString("FormUserProfile:lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormUserProfile_lblPosition {
            get {
                return ResourceManager.GetString("FormUserProfile:lblPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormUserProfile_lblPosition2 {
            get {
                return ResourceManager.GetString("FormUserProfile:lblPosition2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormUserProfile_lblSurname {
            get {
                return ResourceManager.GetString("FormUserProfile:lblSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormUserProfile_lblSurname2 {
            get {
                return ResourceManager.GetString("FormUserProfile:lblSurname2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormUserProfile_lblTittle {
            get {
                return ResourceManager.GetString("FormUserProfile:lblTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormUserProfile_lblUser {
            get {
                return ResourceManager.GetString("FormUserProfile:lblUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormUserProfile_lblUsername {
            get {
                return ResourceManager.GetString("FormUserProfile:lblUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FormUserProfile_lnkEditProfile {
            get {
                return ResourceManager.GetString("FormUserProfile:lnkEditProfile", resourceCulture);
            }
        }
    }
}
